<?php

namespace Dan\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Dan\UserBundle\Entity\User;

/**
 * DesireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesireRepository extends EntityRepository
{
    /**
     * @see EntityRepository
     */
    private $user;    
    public function setUser(User $user) {
        $this->user = $user;
        
        return $this;
    }
    
    /**
     * Get accounts ordered by position
     *
     * @return \DateTime 
     */
    public function findByGameId($gameId) {
//        if (!$this->user) {
//            throw new \Exception('You did not set the user');
//        }
        $user = $this->user;
        $qb = $this->createQueryBuilder('d')
                ->where("d.gameId = :gameId")
                ->setParameter('gameId', $gameId);
        if ($user) {
            $qb->andWhere("d.user = :user")
                ->setParameter('user', $user);
        }
        return $qb->getQuery()->getResult();
    }
}
