<?php

namespace Dan\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoinRepository extends EntityRepository
{
}
